# -*- coding: utf-8 -*-
"""Natália_Amaral_aula19Pratico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CInX-lf9rtRowrlgqrPjXkAD-I_5nQRb
"""

!pip install --upgrade protobuf tensorflow-metadata tensorflow-datasets

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix
import cv2


# Carregamento dos dados da base: 'colorectal_histology' do TensorFlow
(ds_train, ds_test), ds_info = tfds.load(
    'colorectal_histology',
    split=['train[:70%]', 'train[70%:]'],
    with_info=True,
    as_supervised=True,
)

def preprocessar(imagem, rotulo):
    imagem = tf.cast(imagem, tf.float32) / 255.0
    return imagem, rotulo

BATCH_SIZE = 32

ds_train = ds_train.map(preprocessar).cache().shuffle(1000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
ds_test = ds_test.map(preprocessar).cache().batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# Usei dois modelos de CNN: MobileNetV2 e uma CNN com parâmetros que eu escolhi
# MobileNetV2
modelo_base = tf.keras.applications.MobileNetV2(
    input_shape=(150, 150, 3),
    include_top=False,
    weights='imagenet'
)
modelo_base.trainable = False

modelo_transfer = tf.keras.Sequential([
    tf.keras.Input(shape=(150, 150, 3)),
    modelo_base,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(8, activation='softmax')
])

modelo_transfer.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# CNN personalizada
modelo_custom = tf.keras.Sequential([
    tf.keras.Input(shape=(150, 150, 3)),

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu', name='ultima_conv'),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(8, activation='softmax')
])

modelo_custom.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Fase de treinamento (escolhi 30% para teste)
EPOCHS = 10

print("Treinamento - MobileNetV2")
hist_transfer = modelo_transfer.fit(ds_train, validation_data=ds_test, epochs=EPOCHS)

print("\Treinamento - CNN Personalizada")
hist_custom = modelo_custom.fit(ds_train, validation_data=ds_test, epochs=EPOCHS)

# Avaliação de acurácia e perda
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(hist_transfer.history['val_accuracy'], label='MobileNetV2')
plt.plot(hist_custom.history['val_accuracy'], label='Personalizada')
plt.title('Acurácia')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(hist_transfer.history['val_loss'], label='MobileNetV2')
plt.plot(hist_custom.history['val_loss'], label='Personalizada')
plt.title('Perda')
plt.legend()
plt.show()

rotulos_reais = np.concatenate([y for x, y in ds_test], axis=0)
pred_transfer = np.argmax(modelo_transfer.predict(ds_test), axis=-1)
pred_custom = np.argmax(modelo_custom.predict(ds_test), axis=-1)

classes = ['Tumor', 'Estroma Simp.', 'Estroma Comp.', 'Imune', 'Residuos', 'Glandulas', 'Adiposo', 'Fundo']

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.heatmap(confusion_matrix(rotulos_reais, pred_transfer), annot=True, fmt='d', cmap='Blues',
            xticklabels=classes, yticklabels=classes, ax=axes[0])
axes[0].set_title('Matriz de Confusão - MobileNetV2')

sns.heatmap(confusion_matrix(rotulos_reais, pred_custom), annot=True, fmt='d', cmap='Oranges',
            xticklabels=classes, yticklabels=classes, ax=axes[1])
axes[1].set_title('Matriz de Confusão - CNN personalizada')
plt.tight_layout()
plt.show()

# Grad_CAM
print("\nGerando os mapas de calor e salvando PDF")

def plotar_cam(img_orig, heatmap, titulo):
    heatmap = np.nan_to_num(heatmap)

    heatmap_resized = cv2.resize(heatmap, (img_orig.shape[1], img_orig.shape[0]))
    heatmap_color = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    img_mista = cv2.addWeighted(np.uint8(255 * img_orig), 0.6, heatmap_color, 0.4, 0)
    plt.imshow(img_mista)
    plt.title(titulo)
    plt.axis('off')

# Pegando apenas uma imagem do dataset de teste para analisar o resultado
for imgs, labels in ds_test.take(1):
    img_alvo = imgs[0]
    img_tensor = tf.expand_dims(img_alvo, axis=0)
    rotulo_alvo = labels[0].numpy()
    break

# Grad-CAM 1: MobileNetV2
with tf.GradientTape() as tape:
    mapa_conv_transfer = modelo_base(img_tensor)
    tape.watch(mapa_conv_transfer)
    x = modelo_transfer.layers[1](mapa_conv_transfer)
    predicoes_transfer = modelo_transfer.layers[2](x)

    idx_transfer = tf.argmax(predicoes_transfer[0])
    prob_alvo_transfer = predicoes_transfer[:, idx_transfer]

grads_transfer = tape.gradient(prob_alvo_transfer, mapa_conv_transfer)
pesos_transfer = tf.reduce_mean(grads_transfer, axis=(0, 1, 2))
cam_transfer = tf.reduce_sum(tf.multiply(pesos_transfer, mapa_conv_transfer), axis=-1)
cam_transfer = tf.nn.relu(cam_transfer)
cam_transfer = tf.squeeze(cam_transfer)
cam_transfer = cam_transfer / (tf.reduce_max(cam_transfer) + 1e-8)
cam_transfer = cam_transfer.numpy()

# Grad-CAM 2: CNN personalizada
with tf.GradientTape() as tape:
    tensor_atual = img_tensor
    indice_corte = 0
    for i, camada in enumerate(modelo_custom.layers):
        tensor_atual = camada(tensor_atual)
        if camada.name == 'ultima_conv':
            mapa_conv_custom = tensor_atual
            indice_corte = i
            break

    tape.watch(mapa_conv_custom)

    saida_atual = mapa_conv_custom
    for camada in modelo_custom.layers[indice_corte + 1:]:
        saida_atual = camada(saida_atual)

    predicoes_custom = saida_atual
    idx_custom = tf.argmax(predicoes_custom[0])
    prob_alvo_custom = predicoes_custom[:, idx_custom]

grads_custom = tape.gradient(prob_alvo_custom, mapa_conv_custom)
pesos_custom = tf.reduce_mean(grads_custom, axis=(0, 1, 2))
cam_custom = tf.reduce_sum(tf.multiply(pesos_custom, mapa_conv_custom), axis=-1)
cam_custom = tf.nn.relu(cam_custom)
cam_custom = tf.squeeze(cam_custom)
cam_custom = cam_custom / (tf.reduce_max(cam_custom) + 1e-8)
cam_custom = cam_custom.numpy()


# Plot Final
figura_final = plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(img_alvo.numpy())
plt.title(f'Imagem Original\nRótulo Real: {classes[rotulo_alvo]}', fontsize=14)
plt.axis('off')

plt.subplot(1, 3, 2)
plotar_cam(img_alvo.numpy(), cam_transfer, f'Grad-CAM: MobileNetV2\nPredição: {classes[idx_transfer]}')

plt.subplot(1, 3, 3)
plotar_cam(img_alvo.numpy(), cam_custom, f'Grad-CAM: Customizada\nPredição: {classes[idx_custom]}')

plt.tight_layout()

nome_arquivo_pdf = "gradcam_comparacao_modelos.pdf"
plt.savefig(nome_arquivo_pdf, format='pdf', bbox_inches='tight', dpi=300)
print(f"\nImagem salva no formato PDF: {nome_arquivo_pdf}")

plt.show()

# Decidi gerar um relatório em pdf com 30 imagens geradas pelo Grad-Cam a fim de analisar se a rede está olhando para o local correto
from matplotlib.backends.backend_pdf import PdfPages

caminho_arquivo_pdf = "relatorio_gradcam_30_imagens.pdf"
quantidade_imagens = 30

print(f"Gerando {quantidade_imagens} mapas de calor Grad-CAM")

def plotar_cam(img_orig, heatmap, titulo):
    heatmap = np.nan_to_num(heatmap)
    heatmap_resized = cv2.resize(heatmap, (img_orig.shape[1], img_orig.shape[0]))
    heatmap_color = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    img_mista = cv2.addWeighted(np.uint8(255 * img_orig), 0.6, heatmap_color, 0.4, 0)
    plt.imshow(img_mista)
    plt.title(titulo, fontsize=12)
    plt.axis('off')

# Abre o gerador de PDF que vai empilhar as páginas
with PdfPages(caminho_arquivo_pdf) as gerador_pdf:

    # Cada lote contem 32 imagens, então pegamos apenas 1
    for imagens_lote, rotulos_lote in ds_test.take(1):

        # Iteramos pelas 30 primeiras imagens deste lote
        for indice_imagem in range(quantidade_imagens):

            img_alvo = imagens_lote[indice_imagem]
            img_tensor = tf.expand_dims(img_alvo, axis=0)
            rotulo_alvo = rotulos_lote[indice_imagem].numpy()

            # Grad-CAM: MobileNetV2
            with tf.GradientTape() as tape:
                mapa_conv_transfer = modelo_base(img_tensor)
                tape.watch(mapa_conv_transfer)
                x = modelo_transfer.layers[1](mapa_conv_transfer)
                predicoes_transfer = modelo_transfer.layers[2](x)

                idx_transfer = tf.argmax(predicoes_transfer[0])
                prob_alvo_transfer = predicoes_transfer[:, idx_transfer]

            grads_transfer = tape.gradient(prob_alvo_transfer, mapa_conv_transfer)
            pesos_transfer = tf.reduce_mean(grads_transfer, axis=(0, 1, 2))
            cam_transfer = tf.reduce_sum(tf.multiply(pesos_transfer, mapa_conv_transfer), axis=-1)
            cam_transfer = tf.nn.relu(cam_transfer)
            cam_transfer = tf.squeeze(cam_transfer)
            cam_transfer = cam_transfer / (tf.reduce_max(cam_transfer) + 1e-8)
            cam_transfer = cam_transfer.numpy()

            # Grad-CAM: CNN personalizada
            with tf.GradientTape() as tape:
                tensor_atual = img_tensor
                indice_corte = 0
                for i, camada in enumerate(modelo_custom.layers):
                    tensor_atual = camada(tensor_atual)
                    if camada.name == 'ultima_conv':
                        mapa_conv_custom = tensor_atual
                        indice_corte = i
                        break

                tape.watch(mapa_conv_custom)

                saida_atual = mapa_conv_custom
                for camada in modelo_custom.layers[indice_corte + 1:]:
                    saida_atual = camada(saida_atual)

                predicoes_custom = saida_atual
                idx_custom = tf.argmax(predicoes_custom[0])
                prob_alvo_custom = predicoes_custom[:, idx_custom]

            grads_custom = tape.gradient(prob_alvo_custom, mapa_conv_custom)
            pesos_custom = tf.reduce_mean(grads_custom, axis=(0, 1, 2))
            cam_custom = tf.reduce_sum(tf.multiply(pesos_custom, mapa_conv_custom), axis=-1)
            cam_custom = tf.nn.relu(cam_custom)
            cam_custom = tf.squeeze(cam_custom)
            cam_custom = cam_custom / (tf.reduce_max(cam_custom) + 1e-8)
            cam_custom = cam_custom.numpy()

            # Montagem do pdf
            figura_final = plt.figure(figsize=(18, 6))

            plt.subplot(1, 3, 1)
            plt.imshow(img_alvo.numpy())
            plt.title(f'Imagem {indice_imagem + 1}\nRótulo Real: {classes[rotulo_alvo]}', fontsize=14)
            plt.axis('off')

            plt.subplot(1, 3, 2)
            plotar_cam(img_alvo.numpy(), cam_transfer, f'Grad-CAM: MobileNetV2\nPredição: {classes[idx_transfer]}')

            plt.subplot(1, 3, 3)
            plotar_cam(img_alvo.numpy(), cam_custom, f'Grad-CAM: Customizada\nPredição: {classes[idx_custom]}')

            plt.tight_layout()

            # Salva a figura atual como uma nova página no arquivo PDF
            gerador_pdf.savefig(figura_final, bbox_inches='tight')

            plt.close(figura_final)

            # Log de progresso a cada 5 imagens
            if (indice_imagem + 1) % 5 == 0:
                print(f"\n{indice_imagem + 1}/{quantidade_imagens} imagens processadas")

print(f"\nRelatório salvo no arquivo: {caminho_arquivo_pdf}")